import pytest


from pages.Place_Order_Page import OrderPage
from playwright.sync_api import expect
from data.test_data import Data
from pages.Signup_Login_Page import SignupPage
from utils.tools import take_screenshot
from pages.registr_Page import RegistrPage


class TestContactUs:

    @pytest.fixture
    def test_setup(self, new_page):
        self.page = new_page
        self.order = OrderPage(self.page)
        self.signup = SignupPage(self.page)
        self.registr = RegistrPage(self.page)

    def test_TestCase14_Place_Order_Register_while_Checkout(self, new_page, test_setup):
        self.order.click_add_to_card1()
        self.order.click_view_cart_btn()
        expect(new_page).to_have_url('https://automationexercise.com/view_cart')
        self.order.check_out_btn_click()
        self.order.click_register_login_btn()
        self.signup.input_name(Data.name)
        self.signup.input_email_signup(Data.email)
        self.signup.click_signup_btn()
        self.signup.check_enter_account_information_lbl()
        self.registr.fill_registration_form(Data.password, Data.day, Data.months, Data.years, Data.firstname, Data.lastname, Data.company, Data.address, Data.address2,Data.country, Data.state, Data.city, Data.zipcode, Data.mobilenumber)
        self.signup.check_account_created_lbl()
        self.signup.click_continue_btn()
        self.signup.check_logged_in_as_user_lbl()
        self.order.click_view_cart_button()
        self.order.check_out_btn_click()
        expect(self.order.address_delivery_field).to_contain_text("New street,2")
        self.order.fill_form_control_field(Data.sometext)
        self.order.click_place_order_btn()
        self.order.fill_name_on_card(Data.NameonCard)
        self.order.fill_card_number(Data.CardNumber)
        self.order.fill_cvc_number(Data.CVC)
        self.order.fill_expiry_month(Data.Expiration)
        self.order.fill_expiry_year(Data.date)
        self.order.click_pay_button()
        self.order.check_success_message()
        self.signup.click_delete_account_btn()
        self.signup.check_delete_account_lbl()
        self.signup.click_continue_btn2()
        take_screenshot(self.page, "Place_Order_Register_while_Checkout")

    def test_TestCase15_Place_Order_Register_before_Checkout(self, new_page, test_setup):
        self.signup.click_signup_login_btn()
        self.signup.input_name(Data.name)
        self.signup.input_email_signup(Data.email)
        self.signup.click_signup_btn()
        self.signup.check_enter_account_information_lbl()
        self.registr.fill_registration_form(Data.password, Data.day, Data.months, Data.years, Data.firstname, Data.lastname, Data.company, Data.address, Data.address2,Data.country, Data.state, Data.city, Data.zipcode, Data.mobilenumber)
        self.signup.check_account_created_lbl()
        self.signup.click_continue_btn()
        self.signup.check_logged_in_as_user_lbl()
        self.order.click_add_to_card1()
        self.order.click_view_cart_btn()
        expect(new_page).to_have_url('https://automationexercise.com/view_cart')
        self.order.check_out_btn_click()
        expect(self.order.address_delivery_field).to_contain_text("New street,2")
        self.order.fill_form_control_field(Data.sometext)
        self.order.click_place_order_btn()
        self.order.fill_name_on_card(Data.NameonCard)
        self.order.fill_card_number(Data.CardNumber)
        self.order.fill_cvc_number(Data.CVC)
        self.order.fill_expiry_month(Data.Expiration)
        self.order.fill_expiry_year(Data.date)
        self.order.click_pay_button()
        self.order.check_success_message()
        self.signup.click_delete_account_btn()
        self.signup.check_delete_account_lbl()
        self.signup.click_continue_btn2()
        take_screenshot(self.page, "Place_Order_Register_before_Checkout")

    def test_TestCase16_Login_before_Checkout(self, new_page, test_setup):
        self.signup.click_signup_login_btn()
        self.signup.input_login_email_address_to_field(Data.email4)
        self.signup.input_login_password_to_field(Data.password)
        self.signup.click_login_btn()
        self.order.click_add_to_card1()
        self.order.click_view_cart_btn()
        expect(new_page).to_have_url('https://automationexercise.com/view_cart')
        self.order.check_out_btn_click()
        expect(self.order.address_delivery_field).to_contain_text("New street,2")
        self.order.fill_form_control_field(Data.sometext)
        self.order.click_place_order_btn()
        self.order.fill_name_on_card(Data.NameonCard)
        self.order.fill_card_number(Data.CardNumber)
        self.order.fill_cvc_number(Data.CVC)
        self.order.fill_expiry_month(Data.Expiration)
        self.order.fill_expiry_year(Data.date)
        self.order.click_pay_button()
        self.order.check_success_message()
        self.signup.click_delete_account_btn()
        self.signup.check_delete_account_lbl()
        self.signup.click_continue_btn2()
        take_screenshot(self.page, "Login_before_Checkout")
        self.signup.click_signup_login_btn()
        self.signup.input_name(Data.name)
        self.signup.input_email_signup(Data.email4)
        self.signup.click_signup_btn()
        self.registr.fill_registration_form(Data.password, Data.day, Data.months, Data.years, Data.firstname, Data.lastname, Data.company, Data.address, Data.address2,Data.country, Data.state, Data.city, Data.zipcode, Data.mobilenumber)

    def test_TestCase23_Verify_address_details_in_checkout_page(self, new_page, test_setup):
        self.signup.click_signup_login_btn()
        self.signup.input_name(Data.name)
        self.signup.input_email_signup(Data.email)
        self.signup.click_signup_btn()
        self.signup.check_enter_account_information_lbl()
        self.registr.fill_registration_form(Data.password, Data.day, Data.months, Data.years, Data.firstname,Data.lastname, Data.company, Data.address, Data.address2, Data.country,Data.state, Data.city, Data.zipcode, Data.mobilenumber)
        self.signup.check_account_created_lbl()
        self.signup.click_continue_btn()
        self.signup.check_logged_in_as_user_lbl()
        self.order.click_add_to_card1()
        self.order.click_view_cart_btn()
        expect(new_page).to_have_url('https://automationexercise.com/view_cart')
        self.order.check_out_btn_click()
        expect(self.order.address_delivery_field).to_contain_text("New street,2")
        expect(self.order.address_billing_field).to_contain_text("New street,22")
        self.signup.click_delete_account_btn()
        self.signup.check_delete_account_lbl()
        self.signup.click_continue_btn2()
        take_screenshot(self.page, "Verify_address_details_in_checkout_page")

    def test_TestCase24_Download_Invoice_after_purchase_order(self, new_page, test_setup, file=None):
        self.order.click_add_to_card1()
        self.order.click_view_cart_btn()
        expect(new_page).to_have_url('https://automationexercise.com/view_cart')
        self.order.check_out_btn_click()
        self.signup.click_register_login()
        self.signup.input_name(Data.name)
        self.signup.input_email_signup(Data.email)
        self.signup.click_signup_btn()
        self.signup.check_enter_account_information_lbl()
        self.registr.fill_registration_form(Data.password, Data.day, Data.months, Data.years, Data.firstname, Data.lastname, Data.company, Data.address, Data.address2, Data.country,Data.state, Data.city, Data.zipcode, Data.mobilenumber)
        self.signup.check_account_created_lbl()
        self.signup.click_continue_btn()
        self.signup.check_logged_in_as_user_lbl()
        self.order.click_view_cart_button()
        self.order.check_out_btn_click()
        expect(self.order.address_delivery_field).to_contain_text("New street,2")
        self.order.fill_form_control_field(Data.sometext)
        self.order.click_place_order_btn()
        self.order.fill_name_on_card(Data.NameonCard)
        self.order.fill_card_number(Data.CardNumber)
        self.order.fill_cvc_number(Data.CVC)
        self.order.fill_expiry_month(Data.Expiration)
        self.order.fill_expiry_year(Data.date)
        self.order.click_pay_button()
        self.order.check_success_message()
        self.order.click_download_invoice_btn()
        self.order.check_downloaded_file()
        self.signup.click_continue_btn2()
        self.signup.click_delete_account_btn()
        self.signup.check_delete_account_lbl()
        take_screenshot(self.page, "Download_Invoice_after_purchase_order")
